### ISSUE TITLE
Is someone maintaining this library ?

### ISSUE THREAD

**Issue by krazykira** [oli107/material-range-bar#97]
If someone is maintaining this library then kindly Review the PRs otherwise i am thinking i should adopt this library. 

Kindly let me know if you agree

**Comment by alextorres50** [comment]
its a great idea

**Comment by nosph** [comment]
+

**Comment by oli107** [comment]
Apologies for the lack of response to all issues/PRs. I built this library for a single project (and it works flawlessly in that environment) and have since been carried away with it. I am happy to add you as a contributor to help clear the issues and I can hopefully get some time to have a go at it also soon.

**Comment by krazykira** [comment]
Hi @oli107   kindly send me an email, i have some confusion related to how you generated the gradle library path for Material Range bar. Lets talk about that. You can find my email under my profile

**Comment by krazykira** [comment]
@oli107 Hey can you please send me an email. There is something related to collaborators that i want to talk about. Its kind of urgent
